# Generated by Django 4.2.4 on 2023-10-22 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='email',
            field=models.EmailField(default='students@softuni.bg', max_length=254, unique=True),
        ),
    ]
