"""adding some models and functionalities

Revision ID: 2e65bdc7b79b
Revises: 732f1852cd3c
Create Date: 2023-12-14 19:55:33.538135

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2e65bdc7b79b'
down_revision: Union[str, None] = '732f1852cd3c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
