# Generated by Django 4.2.4 on 2023-10-22 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_alter_project_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='estimated_hours',
            field=models.FloatField(blank=True, null=True, verbose_name='Estimated Hours'),
        ),
    ]
